# Generated by Django 5.2.6 on 2025-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='เลขทะเบียน')),
                ('province', models.CharField(max_length=100, verbose_name='จังหวัด')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='เวลาเข้า')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='เวลาออก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
