# Generated by Django 5.2.6 on 2025-09-29 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='check_in',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='เวลาเข้า'),
        ),
    ]
