# Generated by Django 5.2.6 on 2025-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_licenseplate_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='รูปรถ'),
        ),
    ]
